language: node_js
node_js:
  - "stable"
  - "lts/*"
sudo: false
services:
  - docker
  - mongodb

# We need to download MongoDB 2.6.10
env:
  global:
    - MONGODB_VERSION=2.6.10
before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db > /dev/null 2>&1 &
  - sleep 3

# allowlist
branches:
  only:
    - master
