module.exports = {
  modules: {
    '@apostrophecms/error': {},
    '@apostrophecms/util': {},
    '@apostrophecms/task': {},
    '@apostrophecms/schema': {},
    '@apostrophecms/asset': {},
    '@apostrophecms/launder': {},
    '@apostrophecms/http': {},
    '@apostrophecms/i18n': {},
    '@apostrophecms/attachment': {},
    '@apostrophecms/db': {},
    '@apostrophecms/lock': {},
    '@apostrophecms/cache': {},
    '@apostrophecms/migration': {},
    '@apostrophecms/express': {},
    '@apostrophecms/url': {},
    '@apostrophecms/template': {},
    '@apostrophecms/email': {},
    '@apostrophecms/permission': {},
    '@apostrophecms/admin-bar': {},
    '@apostrophecms/notification': {},
    '@apostrophecms/login': {},
    '@apostrophecms/doc': {},
    '@apostrophecms/job': {},
    '@apostrophecms/modal': {},
    '@apostrophecms/oembed': {},
    '@apostrophecms/pager': {},
    '@apostrophecms/any-doc-type': {},
    // global comes first so it can register a doc type manager and clean things up before
    // pages claims any orphan page types
    '@apostrophecms/global': {},
    '@apostrophecms/polymorphic-type': {},
    '@apostrophecms/page': {},
    '@apostrophecms/home-page': {},
    '@apostrophecms/trash': {},
    '@apostrophecms/search': {},
    '@apostrophecms/any-page-type': {},
    '@apostrophecms/area': {},
    '@apostrophecms/rich-text-widget': {},
    '@apostrophecms/html-widget': {},
    '@apostrophecms/image-widget': {},
    '@apostrophecms/oembed-field': {},
    '@apostrophecms/video-widget': {},
    '@apostrophecms/ui': {},
    '@apostrophecms/user': {},
    '@apostrophecms/image': {},
    '@apostrophecms/image-tag': {},
    '@apostrophecms/file': {},
    '@apostrophecms/file-tag': {},
    '@apostrophecms/soft-redirect': {},
    '@apostrophecms/storybook': {},
    '@apostrophecms/busy': {}
  }
};
