{
  "name": "apostrophe",
  "version": "3.3.1",
  "description": "The Apostrophe Content Management System.",
  "main": "index.js",
  "scripts": {
    "pretest": "npm run lint && npm audit",
    "test": "nyc --reporter=html mocha -t 10000",
    "lint": "eslint . && node scripts/lint-i18n"
  },
  "repository": {
    "type": "git",
    "url": "git@github.com:apostrophecms/apostrophe.git"
  },
  "engines": {
    "node": ">=12.0.0"
  },
  "keywords": [
    "apostrophe",
    "apostrophe-cms",
    "apostrophecms",
    "cms",
    "node cms",
    "headless cms",
    "content management system"
  ],
  "author": "Apostrophe Technologies, Inc.",
  "license": "MIT",
  "dependencies": {
    "@apostrophecms/vue-color": "^2.8.2",
    "@babel/core": "^7.14.3",
    "@babel/preset-env": "^7.14.4",
    "@tiptap/extension-highlight": "^2.0.0-beta.13",
    "@tiptap/extension-link": "^2.0.0-beta.17",
    "@tiptap/extension-text-align": "^2.0.0-beta.17",
    "@tiptap/extension-text-style": "^2.0.0-beta.13",
    "@tiptap/extension-underline": "^2.0.0-beta.14",
    "@tiptap/starter-kit": "^2.0.0-beta.75",
    "@tiptap/vue-2": "^2.0.0-beta.34",
    "autoprefixer": "^10.2.4",
    "babel-loader": "^8.2.2",
    "bluebird": "^3.7.2",
    "body-parser": "^1.18.2",
    "boring": "^1.1.1",
    "broadband": "^1.1.0",
    "cheerio": "^1.0.0-rc.10",
    "chokidar": "^3.5.2",
    "common-tags": "^1.8.0",
    "connect-mongo": "^3.0.0",
    "connect-multiparty": "^2.1.1",
    "cookie-parser": "^1.4.5",
    "core-js": "~3.14.0",
    "cors": "^2.8.5",
    "credential": "^2.0.0",
    "css-loader": "^5.2.4",
    "cuid": "^1.3.8",
    "dayjs": "^1.9.8",
    "debounce-async": "0.0.2",
    "deep-get-set": "^1.1.1",
    "eslint-plugin-promise": "^5.1.0",
    "express": "^4.16.4",
    "express-bearer-token": "^2.4.0",
    "express-session": "^1.17.1",
    "form-data": "^4.0.0",
    "fs-extra": "^7.0.1",
    "glob": "^5.0.15",
    "he": "^0.5.0",
    "html-to-text": "^5.1.1",
    "i18next": "^20.3.2",
    "i18next-http-middleware": "^3.1.4",
    "import-fresh": "^3.3.0",
    "is-wsl": "^2.2.0",
    "klona": "^2.0.4",
    "launder": "^1.4.0",
    "lodash": "^4.17.20",
    "mini-css-extract-plugin": "^1.6.0",
    "minimatch": "^3.0.4",
    "mkdirp": "^0.5.5",
    "mongodb": "^3.6.6",
    "node-fetch": "^2.6.1",
    "nodemailer": "^6.6.1",
    "nunjucks": "^3.2.1",
    "oembetter": "^1.0.1",
    "passport": "^0.3.2",
    "passport-local": "^1.0.0",
    "path-to-regexp": "^1.8.0",
    "performance-now": "^2.1.0",
    "postcss-loader": "^5.0.0",
    "prompts": "^2.4.1",
    "qs": "^6.10.1",
    "regenerator-runtime": "^0.13.7",
    "regexp-quote": "0.0.0",
    "resolve": "^1.19.0",
    "resolve-from": "^5.0.0",
    "sanitize-html": "^2.0.0",
    "sass": "^1.34.1",
    "sass-loader": "^10.1.1",
    "server-destroy": "^1.0.1",
    "sluggo": "^0.3.0",
    "stylelint": "^13.13.0",
    "stylelint-config-standard": "^20.0.0",
    "stylelint-declaration-strict-value": "^1.7.12",
    "stylelint-order": "^4.1.0",
    "stylelint-webpack-plugin": "^2.1.1",
    "tinycolor2": "^1.4.2",
    "tough-cookie": "^4.0.0",
    "underscore.string": "^3.3.4",
    "uploadfs": "^1.17.1",
    "v-tooltip": "^2.0.3",
    "vue": "^2.6.14",
    "vue-click-outside-element": "^1.0.13",
    "vue-loader": "^15.9.6",
    "vue-material-design-icons": "^4.9.0",
    "vue-style-loader": "^4.1.2",
    "vue-template-compiler": "^2.6.14",
    "vuedraggable": "^2.24.3",
    "webpack": "~5.44.0",
    "webpack-merge": "^5.7.3",
    "xregexp": "^2.0.0"
  },
  "devDependencies": {
    "babel-eslint": "^10.1.0",
    "eslint": "^7.25.0",
    "eslint-config-apostrophe": "^3.4.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-vue": "^7.9.0",
    "mocha": "^7.1.2",
    "nyc": "^15.1.0",
    "replace-in-file": "^6.1.0",
    "vue-eslint-parser": "^7.1.1",
    "webpack-bundle-analyzer": "^3.9.0"
  },
  "browserslist": [
    "ie >= 10"
  ]
}
