/* tslint:disable */
/* eslint-disable */
/**
 * ApostropheCMS REST API
 * **🚀 The headless CMS that developers actually want to use**  **For production use:** Download this YAML file and update the server URL and cookie names to match your setup.  The ApostropheCMS REST API allows you to create, read, update, and delete content programmatically. Perfect for building modern websites, mobile apps, and any digital experience that needs flexible content management.  ## Quick Start Guide 1. **Authentication**: Use the login endpoint to get a bearer token or session cookie 2. **Get Content**: Start with `/@apostrophecms/page` to fetch your page structure 3. **Media Files**: Upload files via `/@apostrophecms/attachment/upload` 4. **Internationalization**: Use `/@apostrophecms/i18n` to localize your content  ## Content Architecture ApostropheCMS uses a flexible \"pieces\" system for content types. While the core system provides essential pieces like users and global content, most projects define custom piece types like articles, events, or products using the `@apostrophecms/piece-type` module.  ## Built-in Piece Types - `@apostrophecms/user` - User accounts and profiles - `@apostrophecms/global` - Site-wide content (customizable with additional fields) - `@apostrophecms/image` - Image file management - `@apostrophecms/file` - General file management (PDFs, documents, etc.)  ## Built-in Tag Types - `@apostrophecms/image-tag` - Tags for organizing images - `@apostrophecms/file-tag` - Tags for organizing files  ## Authentication Methods - **Bearer Token**: Recommended for API clients and SPAs - **Session Cookie**: For traditional web applications - **API Key**: For server-to-server communication  ## Rate Limiting API requests are rate-limited to prevent abuse. See response headers for current limits. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@apostrophecms.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

