#!/bin/bash

if [ -z "$TEST_WITH_PRO" ]; then
  echo "Not testing with Pro modules"
  exit 0
fi

echo "Removing dependencies on Pro modules for testing"

pnpm remove @apostrophecms-pro/automatic-translation
