/**
 * Mocha setup — runs before all specs.
 *
 * Creates stub ESM packages for modules that only exist at runtime
 * inside Vite (generated by vite-plugin-apostrophe-generated-config).
 * Without these stubs Node can't resolve the specifiers and esmock
 * can't intercept them.
 *
 * These stubs provide safe no-op defaults; individual tests override
 * them via esmock as needed.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(fileURLToPath(new URL('.', import.meta.url)), '..');

await mkdir(join(root, 'node_modules', 'apostrophe-astro-config'), { recursive: true });

await writeFile(
  join(root, 'node_modules', 'apostrophe-astro-config', 'package.json'),
  JSON.stringify({
    name: 'apostrophe-astro-config',
    type: 'module',
    exports: {
      './config': './config.js',
      './doctypes': './doctypes.js'
    }
  }, null, 2)
);

await writeFile(
  join(root, 'node_modules', 'apostrophe-astro-config', 'config.js'),
  // Default values — overridden per test via esmock
  'export default { aposHost: "http://localhost:3000", aposPrefix: "", staticBuild: null, excludeRequestHeaders: [] };\n'
);

await writeFile(
  join(root, 'node_modules', 'apostrophe-astro-config', 'doctypes.js'),
  'export const onBeforeWidgetRenderHook = null;\nexport default {};\n'
);
